In [0]:
# Numpy é uma biblioteca fundamental do Python para computação científica
# Fornece funcionalidades relacionadas com arrays
# Tem nível mais elevado de desempenho


In [1]:
import numpy as np
c = np.array([1,2,3,4])
print(type(c))


<class 'numpy.ndarray'>


In [0]:
# Criar array
a = np.array([1,2,3,4])



In [0]:
#Shape, rank e size:
shape = a.shape
rank = np.ndim(a)
tamanho = a.size


In [8]:
print(shape)

(4,)


In [9]:
print(rank)

1


In [10]:
print(tamanho)

4


In [0]:
#Um array bidimensional (matriz):
b = np.array([[1,2,3],[4,5,6]]) 


In [0]:
#Que informaçao se pode obter sobre esse array:
shape = b.shape
rank = np.ndim(b)
tamanho = a.size

In [14]:
print(shape)

(2, 3)


In [15]:
print(rank)

2


In [16]:
print(tamanho)

4


In [17]:
#Alterar valor a array:
a[2]=50
print(a)

[ 1  2 50  4]


In [18]:
#criar um array só com zeros

a = np.zeros((2,2))   
print(a) 


[[0. 0.]
 [0. 0.]]


In [19]:
#Criar array só com uns

b = np.ones((1,2))    
print(b) 


[[1. 1.]]


In [20]:
#criar matriz identidade 3x3

d = np.eye(3)        
print(d)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
#Criar array preenchido com números aleatórios

e = np.random.random((4,4))  
print(e)                     


[[0.43328408 0.9861499  0.8815236  0.64102527]
 [0.02218057 0.01633686 0.31912856 0.47498102]
 [0.88543413 0.38508688 0.17297152 0.15338523]
 [0.08430867 0.72481275 0.371543   0.54251467]]


In [22]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [30]:
#fatiar (slicing) arrays
#numero de linhas, numero de colunas
#linha do inicio a 3, colunas a da 1 (segunda) até à 3

b = a[:3, 1:3]

print(b)


[[ 2  3]
 [ 6  7]
 [10 11]]


In [0]:
b[0, 0] = 99 


In [32]:
print(b)

[[99  3]
 [ 6  7]
 [10 11]]


In [33]:
# Utilização de índices
# criar um novo array 
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [0]:
#criar um array de indices
	
	b = np.array([0, 2, 0, 1])


In [36]:
#Seleccionar um elemento de cada coluna usando os indices de b, isto é, selecciona:
#o elemento com indice 0 na primeira linha
#o elemento com indice 2 na segunda linha
#o elemento com indice 0 na terceira linha
#o elemento com idnice 1 na quarta linha

print(a[np.arange(4), b])

[ 1  6  7 11]


In [37]:
#Pode-se por exemplo mudar os elemento de cada coluna de acordo com o array de indices. 
#Por hipotese adicione-se 10, mas só aos valores encontrados

a[np.arange(4), b] += 10

print(a) 

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]
